### ISSUE TITLE
Support for measuring JVMCI threads does not work with JDK 9

### ISSUE THREAD

**Issue by ceresek** [D-iii-S/java-ubench-agent#6]
Trying to measure JVMCI threads with JDK 9 ends with an exception:

Exception in thread "main" cz.cuni.mff.d3s.perf.MeasurementException: PAPI_attach failed: Invalid argument.
	at cz.cuni.mff.d3s.perf.Measurement.createAttachedEventSetNative(Native Method)
	at cz.cuni.mff.d3s.perf.Measurement.createAttachedEventSet(Measurement.java:27)
	at cz.cuni.mff.d3s.perf.SamplingHelper.lambda$__initJvmciExtraEvents$0(SamplingHelper.java:283)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1494)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.IntPipeline.toArray(IntPipeline.java:516)
	at cz.cuni.mff.d3s.perf.SamplingHelper.__initJvmciExtraEvents(SamplingHelper.java:286)
	at cz.cuni.mff.d3s.perf.SamplingHelper.<init>(SamplingHelper.java:201)
	at cz.cuni.mff.d3s.perf.SamplingHelper.<init>(SamplingHelper.java:153)
	at spec.harness.LaunchPlain.main(LaunchPlain.java:38)

**Comment by vhotspur** [comment]
It looks that in JRE9 the JVMCI threads are not announced via `JVMTI_EVENT_THREAD_START`. Thus the agent cannot map between Java thread id and PAPI (Linux) thread id. Thus, with JRE9 it is not possible to measure JVMCI threads.

I will try to find out whether there is some other way to get the mapping of thread ids.

> Exception in thread "main" cz.cuni.mff.d3s.perf.MeasurementException: PAPI_attach failed: Invalid argument.

This was a bug in the code and the error is misleading. Now, it should throw _"Unknown thread (not registered with PAPI)."_.

**Comment by vhotspur** [comment]
> I will try to find out whether there is some other way to get the mapping of thread ids.

Trying to piggyback on the `JVMTI_EVENT_COMPILED_METHOD_LOAD` does not work as this notification is sent from a service thread (not from the individual JVMCI threads).

One last thing to try is to modify the `Thread` class to register itself somehow but that would require a bit more work.
